baseURL = "https://jindam_news/"
canonifyURLs = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

staticDir = ["static", "themes/Niello/static"]

theme = "Niello"

# md ì•ˆì— html ë„£ì„ë•Œ
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
	[languages.en]
		languageCode = "en-us"
		LanguageName = "ğŸ‡ºğŸ‡¸EN"
		contentDir = "content/en"
		weight = 1
		[[languages.en.menus.main]]
			name = 'Home'
			pageRef = '/'
			weight = 1
		[[languages.en.menus.main]]
			name = 'Categories'
			pageRef = '/categories'
			weight = 2
		[[languages.en.menus.main]]
			name = 'Tags'
			pageRef = '/tags'
			weight = 3
	[languages.zh]
        languageCode = "zh-cn"
        LanguageName = "ğŸ‡¨ğŸ‡³CN"
        contentDir = "content/zh"
        weight = 2
		[[languages.zh.menus.main]]
			name = 'exampleé¦–é¡µ'
			pageRef = '/'
			weight = 1
		[[languages.zh.menus.main]]
			name = 'exampleæ–‡ç« åˆ†ç±»'
			pageRef = '/categories'
			weight = 2
		[[languages.zh.menus.main]]
			name = 'exampleæ ‡ç­¾'
			pageRef = '/tags'
			weight = 3

[params]
    instagram = "https://www.instagram.com/jindam.cau"
[params.google]
	google_ad_client = "******"
	ga4 = "******"
[params.bannershowcase]
	categories = ["ì¶”ì²œ"]
	limit = 4
[params.email]
	contact = "editor@jindam.news"
[params.ignore]
	categories = ["privacy", "terms", "archives", "cookie"]
[params.license]
	copyright = "&#xA9; 2019 ~ 2025 by <a href='https://jindam.news/'>jindam.news/</a> All Rights Reserved."
[params.share]
	sharethis = "******"
[params.disqus]
	shortname = "guangmean"

[outputs]
  home = ["HTML", "JSON"]   # Optional - JSON just for search
